# Generated by Django 5.0 on 2024-06-21 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('company_id', models.IntegerField()),
                ('area_id', models.IntegerField()),
                ('area_name', models.CharField(max_length=100)),
                ('post_id', models.IntegerField()),
                ('post_name', models.CharField(max_length=100)),
                ('user_name', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=100)),
            ],
        ),
    ]
